"""init — scan the repository, write config.toml and program.md."""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from collections.abc import Sequence
from pathlib import Path

from autor3search_python import config, discover, gitx, pipeline, results, templates
from autor3search_python.cli.main import EXIT_OK, EXIT_USAGE

# ".autor3search/*" ignores everything the harness writes under that directory
# (profile output, for instance); the negation re-includes config.toml, the one
# file there meant to be version-controlled since humans own it. Note the "/*":
# git cannot re-include a file whose parent DIRECTORY is excluded, so
# ".autor3search/" plus a negation would silently fail.
#
# The two output paths are IMPORTED, never spelled again: results.tsv is parsed
# strictly by `report` and run.log is the transcript `eval` holds open, so a
# rename that left a literal here would quietly start committing the file it
# was meant to ignore.
#
# The bytecode entries are not tidiness. compile_gate runs compileall and
# pytest writes bytecode too, so without them program.md's `git add -A` commits
# a `__pycache__` tree that changes on every experiment.
GITIGNORE_ENTRIES = (
    ".autor3search/*",
    "!.autor3search/config.toml",
    results.PATH,
    pipeline.RUN_LOG_NAME,
    pipeline.RUN_LOG_BACKUP_NAME,  # rotate_run_log's one backup; see pipeline.py
    "__pycache__/",
    "*.py[cod]",
)


def default_tag() -> str:
    """Suggest a run tag from today's date, e.g. "sep6"."""
    now = dt.datetime.now()
    return f"{now:%b}".lower() + str(now.day)


def _toml_list(key: str, items: Sequence[str]) -> str:
    if not items:
        return f"{key} = []\n"
    inner = ", ".join(f'"{i}"' for i in items)
    return f"{key} = [{inner}]\n"


def render_config(cfg: config.Config) -> str:
    """Render the config as commented TOML.

    Written by hand rather than serialized, so every knob carries the
    explanation a human needs without leaving the file.
    """
    b: list[str] = []
    b.append("# autor3search-python run configuration.\n")
    b.append("# Generated by `autor3search-python init`. Safe to hand-edit; init only\n")
    b.append("# writes this file once (or with -force), so your comments survive.\n")
    b.append("#\n")
    b.append("# This file is hashed at `baseline` time. Any change to it fails every\n")
    b.append("# subsequent eval with reason `config_changed` — the scoring rules are\n")
    b.append("# fixed for the life of a run. To change them, start a new run.\n\n")

    b.append("# Which benchmarks count toward the score. Discovered by `init`; edit by\n")
    b.append("# hand to narrow or widen. A name without a parametrization suffix matches\n")
    b.append("# every parametrization of it. Empty means every discovered benchmark.\n")
    b.append(_toml_list("benchmarks", cfg.benchmarks))
    b.append("\n")

    b.append("# Which paths the agent may edit. Anything outside is rejected by the\n")
    b.append("# scope gate before the change is even compiled. Accepts './...',\n")
    b.append("# 'src/...', 'src/**', 'src/' (all recursive) and 'src' (direct children).\n")
    b.append(_toml_list("scope", cfg.scope))
    b.append("\n")

    b.append("# Interleaved A/B measurement rounds per side. Higher is slower but more\n")
    b.append("# resistant to noise. 4 is a hard floor: below it the significance test can\n")
    b.append("# never report p < 0.05, so every experiment would be discarded no matter\n")
    b.append("# how large the real improvement is. The default of 10 leaves real margin.\n")
    b.append(f"count = {cfg.count}\n\n")

    b.append("# Per-benchmark time budget for one round, passed to pytest-benchmark as\n")
    b.append("# --benchmark-max-time. Must be a duration (1s, 200ms), never a fixed\n")
    b.append("# iteration count: a fixed count makes rounds incomparable, because a\n")
    b.append("# candidate twice as fast finishes in half the wall time and is measured\n")
    b.append("# under different thermal conditions.\n")
    b.append(f'benchtime = "{cfg.benchtime}"\n\n')

    b.append("# Minimum inner rounds pytest-benchmark must run before it stops.\n")
    b.append(f"min_rounds = {cfg.min_rounds}\n\n")

    b.append("# Which pytest-benchmark statistic becomes one round's observation:\n")
    b.append("# median (default, the honest central tendency), min (tighter, more\n")
    b.append("# statistical power, but reports a best case) or mean.\n")
    b.append(f'stat = "{cfg.stat}"\n\n')

    b.append("# The largest tolerated statistically significant regression, percent. Any\n")
    b.append("# benchmark regressing more than this rejects the whole experiment,\n")
    b.append("# however good the overall score.\n")
    b.append(f"max_regress_pct = {cfg.max_regress_pct}\n\n")

    b.append("# The smallest geomean improvement KEEP will accept: the score must fall\n")
    b.append("# below 1 - min_effect_pct/100, not merely below 1. A change can be\n")
    b.append("# statistically significant and still too small to be worth a commit in an\n")
    b.append("# unattended loop. Raise it on a noisy machine — it costs you only wins\n")
    b.append("# smaller than the noise you cannot measure anyway.\n")
    b.append(f"min_effect_pct = {cfg.min_effect_pct}\n\n")

    b.append("# Bounds each subprocess phase (compile, import, pytest, one bench round).\n")
    b.append(f'timeout = "{cfg.timeout}"\n\n')

    b.append("# PYTHONHASHSEED for every gate and measurement. Pinning it removes a real\n")
    b.append("# noise source: hash randomization changes dict and set iteration order\n")
    b.append("# run to run, which changes cache behavior and therefore timings. Set to\n")
    b.append("# -1 to leave the environment alone.\n")
    b.append(f"hashseed = {cfg.hashseed}\n\n")

    b.append("# 'enabled' measures reality. 'disabled' passes --benchmark-disable-gc for\n")
    b.append("# quieter but less representative numbers.\n")
    b.append(f'gc = "{cfg.gc}"\n\n')

    b.append("# Extra sys.path entries, relative to whichever tree is being run — the\n")
    b.append("# candidate or the pinned baseline worktree. The tree root and its src/\n")
    b.append("# directory are always added; list anything else your layout needs.\n")
    b.append(_toml_list("pythonpath", cfg.pythonpath))
    b.append("\n")

    b.append("# The interpreter to run gates and benchmarks with. Empty means the one\n")
    b.append("# running the harness.\n")
    b.append(f'python = "{cfg.python}"\n\n')

    b.append("# Files deliberately exempted from the baseline freeze — normally empty.\n")
    b.append("# Only add one if you specifically want the agent to be able to edit it,\n")
    b.append("# understanding that this weakens the guarantee that tests cannot be gamed.\n")
    b.append(_toml_list("unfreeze", cfg.unfreeze))
    b.append("\n")

    b.append("# Pre-measurement gates. The pytest gate is deliberately absent and cannot\n")
    b.append("# be turned off: correctness is the one thing this harness will not trade.\n")
    b.append("[gates]\n")
    b.append(f"compile = {str(cfg.gates.compile_).lower()}\n")
    b.append(f"import = {str(cfg.gates.import_).lower()}\n")
    return "".join(b)


def ensure_gitignore(root: Path, entries: Sequence[str]) -> None:
    """Append whichever entries are not already present, never duplicating one."""
    path = root / ".gitignore"
    try:
        content = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        content = ""
    existing = {line.strip() for line in content.split("\n")}
    missing = [e for e in entries if e not in existing]
    if not missing:
        return
    if content and not content.endswith("\n"):
        content += "\n"
    path.write_text(content + "".join(e + "\n" for e in missing), encoding="utf-8")


def run(args: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="autor3search-python init")
    parser.add_argument("-C", dest="directory", default=".", help="repository root")
    parser.add_argument(
        "-force",
        "--force",
        dest="force",
        action="store_true",
        help="overwrite an existing .autor3search/config.toml",
    )
    opts = parser.parse_args(args)

    try:
        root = Path(gitx.root(opts.directory))
    except gitx.GitError as e:
        print(
            f"autor3search-python init: {opts.directory} is not inside a git repository: {e}",
            file=sys.stderr,
        )
        print(
            "autor3search-python needs git to keep or discard each experiment; "
            "run `git init` first.",
            file=sys.stderr,
        )
        return EXIT_USAGE

    config_path = root / config.CONFIG_PATH
    if config_path.exists() and not opts.force:
        print(
            f"autor3search-python init: {config_path} already exists; pass -force to overwrite",
            file=sys.stderr,
        )
        return EXIT_USAGE

    found = discover.benchmarks(root)
    if not found:
        print(
            "autor3search-python init: no benchmarks found. This tool optimizes what it "
            "can measure and refuses to guess — add a pytest-benchmark benchmark first "
            "(a test taking the `benchmark` fixture), or see the README section "
            '"Repos with no benchmarks".',
            file=sys.stderr,
        )
        return EXIT_USAGE
    names = discover.node_ids(found)

    cfg = config.Config(**{**config.default().__dict__, "benchmarks": tuple(names)})
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(render_config(cfg), encoding="utf-8")

    program_path = root / "program.md"
    program_path.write_text(templates.program_md(), encoding="utf-8")
    ensure_gitignore(root, GITIGNORE_ENTRIES)

    print(f"autor3search-python init: found {len(names)} benchmark(s):")
    for n in names:
        print(f"  - {n}")
    print("\nwrote:")
    print(f"  {config_path}")
    print(f"  {program_path}")
    print("\nnext:")
    print('  git add -A && git commit -m "autor3search-python init"')
    print("  autor3search-python doctor")
    print(f"  autor3search-python baseline -tag {default_tag()}")
    return EXIT_OK
